name: Run integration tests
on: 
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  localstack:
    runs-on: ubuntu-latest
    services: 
      localstack:
        image: localstack/localstack:1.3.1
        ports: 
         - 4566:4566
         - 4510-4559:4510-4559
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Terraform Install
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.3
      - name: Terraform init
        run: |
          cd ./tests/integration_tests/infra
          terraform init
      - name: Terraform apply
        run: |
          cd ./tests/integration_tests/infra
          terraform apply -auto-approve
      - name: check localstack  
        run: |
         curl http://localhost:4566/_localstack/health -i
      - name: Run tests
        run: make run-integration-tests BUCKET=dqg-settings-local S3_HOST=172.17.0.1