name: Run unit tests
on: 
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3  
      - name: run data test unit tests
        run: make run-unit-tests-in-docker
